# -*- coding: utf-8 -*-
"""Copy of CS110_Project7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PP4ouEw-m1i6YqdotIx7JkiXA1wV61ew

# **NOTE:** Use File > Save a copy in Drive to make a copy before doing anything else

# Project 7: Data Exploration and Visualization

### Overview

In this project, you will apply data exploration and visualization techniques to a real-world dataset of your choice. You'll practice using pandas for data analysis and create meaningful visualizations to gain insights from your data. This project builds on your Python programming skills while introducing you to the exciting world of data science.

In [Lab7](https://colab.research.google.com/drive/15QvSh0csZaCU-OuuPIfpWx5wLDDjmqK4?usp=sharing), you explore the titanic dataset and you should use it as a sample and pick a dataset of your interest to do a similar data exploration and visualization.

### Project Objectives

*   Find and select a dataset from a real-world data source
*   Formulate a clear inquiry question based on your chosen dataset


*   Perform exploratory data analysis using pandas functions
*   Create at least two meaningful data visualizations


*   Analyze your findings and answer your inquiry question
*   Reflect on the insights gained through data exploration

### Data Sources
You can choose from various online data sources such as:

* [Kaggle](https://www.kaggle.com/datasets) - Wide variety of datasets
* [data.gov](https://www.data.gov/) - U.S. government data
* [Our World in Data](https://ourworldindata.org/) - Global development data
* [GitHub](https://github.com/datasets) - Curated datasets
* [Google Dataset Search](https://datasetsearch.research.google.com/) - Search for datasets
* Or any other reliable data source you find interesting

## Part 1: Dataset Selection and Initial Exploration

#### TODO Tasks:

1. Select Your Dataset: Choose a dataset that interests you. Make sure it has at least 100 rows and multiple columns with different data types (e.g., numerical, categorical, dates).

Please create either text or code cells in between the TODO tasks to do the work.

Health and Sleep relation
Health and Sleep relation 2024

2. Import Libraries: Import the necessary libraries (pandas, matplotlib, seaborn) at the beginning of your notebook by creating code cells below this text cell.
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
# %matplotlib inline

"""3. Load Your Data: Load your chosen dataset

1.   List item
2.   List item

using pandas and save it to a pandas dataframe. Please create a code cell below this text cell to do it.
"""

import pandas as pd

# Load the dataset
file_path = "/content/Sleep_health_and_lifestyle_dataset.csv"
df = pd.read_csv(file_path)

"""4. Data Summary: Use the following functions to do inital exploration your dataset:

* info() - Display information about the dataset structure
* describe() - Show statistical summary of numerical columns
* head() - Display the first 5 rows (df.head())
* shape - Show the dimensions of the dataset (e.g. df.shape)
* columns - Get the column names (e.g. df.columns)

You may use 5 code cells below this text cell to accomplish it.
"""

df.info()        # Structure, column data types, null values
df.describe()    # Stats (mean, std, min, max) for numerical columns
df.head()        # First 5 rows of data
df.shape         # Rows and columns count
df.columns       # column names

"""5. Inquiry Question: Write a clear, specific question that you want to answer using your dataset by creating a text cell below and **write the question in bold please.**

For example:

* "How has the average temperature changed in major cities over the past decade?"

* "What factors are most strongly correlated with housing prices?"

* "Is there a relationship between education level and income?"

**Inquiry Question: Does stress levels play a role in the duration of peoples sleep?**

## Part 2: Data Visualization and Analysis

#### TODO Tasks:

1. Data Cleaning (if necessary): Check for and handle any missing values, duplicates, or data quality issues.

**NOTE: This could be a daunting task even for seasoned data scientists. My suggestion is to use a dataset that is already clean if you can for the purpose of completing this assignment in a week.**
"""

# Check for missing values
print("Missing values per column:")
print(df.isnull().sum())

# Drop rows with any missing values
df.dropna(inplace=True)

# Remove duplicate rows if any
df.drop_duplicates(inplace=True)

# Confirm cleanup
print("\nData shape after cleaning:", df.shape)

"""Examples:

* Checking for missing values: df.isnull().sum()
* Dropping rows with any missing values: df.dropna(inplace=True)
* Dropping columns with all missing values: df.dropna(axis=1, how='all', inplace=True)
* Removing duplicate row: df.drop_duplicates(inplace=True)

2. Create Visualizations: Create at least 2 different types of visualizations that help answer your research question. Choose from:

* Bar charts
* Line plots
* Scatter plots
* Histograms
* Box plots
* Heatmaps
* Any other appropriate visualization
"""

import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(10, 6))
sns.boxplot(data=df, x='Stress Level', y='Sleep Duration', palette='coolwarm')
plt.title("Sleep Duration by Stress Level")
plt.xlabel("Stress Level")
plt.ylabel("Sleep Duration (hours)")
plt.show()

# Group by Stress Level and calculate the average Sleep Duration
avg_sleep_by_stress = df.groupby('Stress Level')['Sleep Duration'].mean().sort_index()

# Plotting
plt.figure(figsize=(10, 6))
plt.plot(avg_sleep_by_stress.index, avg_sleep_by_stress.values, marker='o', linestyle='-', color='teal')
plt.title('Average Sleep Duration by Stress Level')
plt.xlabel('Stress Level')
plt.ylabel('Average Sleep Duration (hours)')
plt.grid(True)
plt.xticks(avg_sleep_by_stress.index)
plt.tight_layout()
plt.show()

"""3. Customize Your Plots: Make sure your visualizations are clear and informative by:

* Adding appropriate titles
* Labeling axes
* Using colors effectively
* Adding legends when necessary
"""



"""Please create code cells below this to create your visualizations."""

import matplotlib.pyplot as plt

# Group by Stress Level and calculate the average Sleep Duration
avg_sleep_by_stress = df.groupby('Stress Level')['Sleep Duration'].mean().sort_index()

# Plotting
plt.figure(figsize=(10, 6))
plt.plot(
    avg_sleep_by_stress.index,
    avg_sleep_by_stress.values,
    marker='o',
    linestyle='-',
    color='teal',
    label='Avg Sleep Duration'
)

# Title and Labels
plt.title('Average Sleep Duration by Stress Level', fontsize=16)
plt.xlabel('Stress Level', fontsize=12)
plt.ylabel('Average Sleep Duration (hours)', fontsize=12)

plt.grid(True, linestyle='--', alpha=0.6)
plt.xticks(avg_sleep_by_stress.index)
plt.legend(loc='best')

# Layout and Display
plt.tight_layout()
plt.show()

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

file_path = "/content/Sleep_health_and_lifestyle_dataset.csv"
try:
    df = pd.read_csv(file_path)
except FileNotFoundError:
    print(f"Error: File not found at {file_path}")

    exit()
plt.figure(figsize=(10, 6))

# Boxplot with a color palette
sns.boxplot(data=df, x='Stress Level', y='Sleep Duration', palette='coolwarm')


plt.title("Sleep Duration by Stress Level", fontsize=16)
plt.xlabel("Stress Level", fontsize=12)
plt.ylabel("Sleep Duration (hours)", fontsize=12)


plt.grid(True, linestyle='--', alpha=0.5, axis='y')
plt.tight_layout()
plt.show()

"""4. Analysis: Write 1-2 paragraphs discussing:

* Whether your research question can be answered with the available data
* What insights you discovered through your visualizations
* Any unexpected or interesting findings
* Limitations of your analysis
* Suggestions for further investigation

Please create a text cell below this cell to write your analysis.

Through the data set i used in project 7 my answer was answered and my hypothysis was accurate. Stress level does effect sleep and disturbs sleep duration. While doing project 7 i ran into some difficulty and issues regaurding a code error that had to do with my file i imported and connecting it to my code. I solved this issue by refreshing the dowload and reimporting it into collab and corrected my code.

## Submission Requirements

## NOTE: If you use a local dataset, you MUST submit the dataset along with your notebook to get credit.

* Download your notebook as CS110_Project7.ipynb
* Ensure all TODO tasks are completed
* Make sure your code runs without errors
* Include clear comments explaining your work
* Submit the notebook file

## Grading Criteria (4 points)

* Dataset Selection: Appropriate choice of dataset with sufficient complexity
* Inquiry Question: Clear, specific, and answerable with the chosen data
* Data Exploration: Proper use of pandas functions for initial analysis
* Visualizations: At least 2 clear, well-formatted, and relevant plots
* Analysis: Thoughtful interpretation of findings and answer to research question
* Code Quality: Clean, commented, and well-organized code

Remember: The goal is not just to create visualizations, but to use them to gain meaningful insights about your data. Think like a data scientist and let your curiosity guide your exploration!
"""